home/urls.py
from django.urls import path
from home.views import home

app_name = "home"

urlpatterns = [
    path('', home, name='home'),
]

hr/employee/urls.py
from django.urls import path

from hr.employee import views


app_name = "employee"

urlpatterns = [
    path('employee/', views.emplyee_home, name="employee_home"),
    path('employee/<str:pk>', views.employee_view, name="employee_view"),
    path('office/', views.office_home, name="office_home"),
    path('office/<int:pk>', views.office_view, name="office_view"),
    path('title/', views.title_home, name="title_home"),
    path('title/<int:pk>', views.title_view, name="title_view"),
   
]

hr/urls.py
from django.urls import path
from hr import views

app_name = "hr"

urlpatterns = [
    
    
]

management/base/urls.py
from django.urls import path
from management.base import views
app_name = "management_base"

urlpatterns = [
    path('vendor/home', views.vendor_home, name="vendor_home"),
    path('vendor/view/<int:pk>', views.vendor_view, name="vendor_view"),
]

summit_office/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from management import views as mviews
from hr import views as hviews


router = routers.DefaultRouter()
router.register(r'approval', mviews.ApprovalViewSet)
router.register(r'quotation', mviews.QuotationViewSet)
router.register(r'quotation-item', mviews.QuotationItemViewSet)
router.register(r'titlequote', mviews.TitleQuoteViewSet)
router.register(r'titlequote-item', mviews.TitleQuoteItemViewSet)
router.register(r'purchaseorder', mviews.PurchaseOrderViewSet)
router.register(r'purchaseorder-term', mviews.PurchaseOrderTermViewSet)
router.register(r'paymentnote', mviews.PaymentNoteViewSet)
router.register(r'paymentnote-invoice', mviews.PaymentNoteInvoiceViewSet)
router.register(r'paymentnote-approval', mviews.PaymentNoteApprovalViewSet)
router.register(r'paymentothers', mviews.PaymentOthersViewSet)
router.register(r'paymentothers-item', mviews.PaymentOthersItemViewSet)

router.register(r'partitem', mviews.PartItemViewSet)
router.register(r'titleitem', mviews.TitleItemViewSet)
router.register(r'itemtype', mviews.ItemTypeViewSet)
router.register(r'measuringunit', mviews.MeasuringUnitViewSet)

router.register(r'vendor', mviews.VendorViewSet)
router.register(r'vendor-address', mviews.VendorAddressViewSet)
router.register(r'vendor-contact', mviews.VendorContactViewSet)
router.register(r'vendor-account', mviews.VendorAccountViewSet)


router.register(r'title', hviews.TitleViewSet)
router.register(r'office', hviews.OfficeViewSet)
router.register(r'employee', hviews.EmployeeViewSet)
router.register(r'employee-title', hviews.EmployeeTitleViewSet)
router.register(r'employee-office', hviews.EmployeeOfficeViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include("home.urls", namespace='home')),
    path('payment/', include("management.payment.urls", namespace="payment")),
    path('order/', include("management.order.urls", namespace="order")),
    path('approval/', include("management.approval.urls", namespace="approval")),
    path('base/', include("management.base.urls", namespace="management_base")),
    path('', include("hr.employee.urls", namespace="employee")),
    path('api/', include("management.urls", namespace="management")),
    path('api/', include("hr.urls", namespace="hr")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hr/models.py
import datetime
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your models here.
class Office(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    stitle = models.CharField(max_length=10)
    address = models.TextField(null=True, blank=True)
    contact = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    parent = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return '%s' %(self.title)
    
    class Meta:
        ordering = ['id']


class Title(models.Model):
    id=models.IntegerField(primary_key=True)
    title = models.CharField(max_length=50)
    stitle = models.CharField(max_length=15)

    def __str__(self):
        return '%s-%s' % (self.id, self.title)

    class Meta:
        ordering = ["id"]


class Employee(models.Model):
    gender_choices = [
        ('F', 'Female'),
        ('M', 'Male'),
        ('O', 'Other'),
    ]
    
    blood_choices = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    ]
    
    id = models.CharField(max_length=5, primary_key=True)
    birth_date = models.DateField(null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=gender_choices, default="M")
    blood = models.CharField(max_length=5,choices=blood_choices, null=True, blank=True)
    hire_date = models.DateField(null=True, blank=True)
    hire_title = models.ForeignKey(Title, on_delete=models.CASCADE, related_name='hire_title', default=1402)
    hire_office = models.ForeignKey(Office, on_delete=models.CASCADE, related_name='hire_office', default=100)
    present_title = models.ForeignKey(Title, on_delete=models.CASCADE, related_name='present_title', blank=True, null=True)
    present_office = models.ForeignKey(Office, on_delete=models.CASCADE, related_name='present_office', blank=True, null=True)

    def save(self, *args, **kwargs):
        ttl = EmployeeTitle.objects.all().filter(employee=self.id).filter(date__lte=datetime.date.today()).order_by('-date')
        if ttl:
            ttl0 = ttl[0]
            self.present_title = ttl0.title
        else:
            self.present_title = self.hire_title

        off = EmployeeOffice.objects.all().filter(employee=self.id).filter(date__lte=datetime.date.today()).order_by('-date')
        if off:
            off0 = off[0]
            self.present_office = off0.office
        else:
            self.present_office = self.hire_office
        super().save(*args, **kwargs)
    
    def __str__(self):
        return '%s-%s %s'%(self.id, self.first_name, self.last_name)

    def name(self):
        return '%s %s'%(self.first_name, self.last_name)

    class Meta:
        ordering = ["id"]


class EmployeeTitle(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.ForeignKey(Title, on_delete=models.CASCADE)


@receiver(post_save, sender=EmployeeTitle)
def change_title(sender, instance, **kwargs):
    employee = Employee.objects.get(pk=instance.employee.id)
    employee.save()


class EmployeeOffice(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    office = models.ForeignKey(Office, on_delete=models.CASCADE)


@receiver(post_save, sender=EmployeeOffice)
def change_office(sender, instance, **kwargs):
    employee = Employee.objects.get(pk=instance.employee.id)
    employee.save()

hr/employee/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from hr.funs import EmpTitle, EmpOffice


from hr.models import Employee, EmployeeOffice, EmployeeTitle, Office, Title


def emplyee_home(request):
    template_path = "hr/employee/home.html"

    employees = Employee.objects.all()
    paginator = Paginator(employees, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
    'xs': page_obj
    }
    return render(request, template_path, context)


def employee_view(request, pk):
    template_path = "hr/employee/view.html"
    employee = get_object_or_404(Employee, pk=pk)
    employee.titles = EmployeeTitle.objects.all().filter(employee=employee)
    employee.offices = EmployeeOffice.objects.all().filter(employee=employee)

    context = {
        'x': employee

    }

    return render(request, template_path, context)


def office_home(request):
    template_path = "hr/office/home.html"
    offices  = Office.objects.all().order_by('id')
    paginator = Paginator(offices, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'xs': page_obj,
    }
    return render(request, template_path, context)


def office_view(request, pk):
    template_path = "hr/office/view.html"

    office = get_object_or_404(Office, pk=pk)

    context = {
        'x': office,
    }

    return render(request, template_path, context)


def title_home(request):
    template_path = "hr/title/home.html"
    titles = Title.objects.all().order_by('id')
    paginator = Paginator(titles, 10 )
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'xs': page_obj,
    }

    return render(request, template_path, context)


def title_view(request, pk):
    template_path = "hr/title/view.html"
    title = get_object_or_404(Title, pk=pk)
    context = {
        'x': title,
    }

    return render(request, template_path, context)

hr/views.py
from rest_framework import generics, viewsets, permissions
from hr.models import Employee, EmployeeOffice, EmployeeTitle, Office, Title
from hr.serializers import EmployeeOfficeSerializer, EmployeeSerializer, EmployeeTitleSerializer, OfficeSerializer, TitleSerializer



# Create your views here.
class OfficeViewSet(viewsets.ModelViewSet):
    queryset  = Office.objects.all()
    serializer_class = OfficeSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class TitleViewSet(viewsets.ModelViewSet):
    queryset  = Title.objects.all()
    serializer_class = TitleSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset  = Employee.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
                          

class EmployeeTitleViewSet(viewsets.ModelViewSet):
    queryset  = EmployeeTitle.objects.all()
    serializer_class = EmployeeTitleSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

  
class EmployeeOfficeViewSet(viewsets.ModelViewSet):
    queryset  = EmployeeOffice.objects.all()
    serializer_class = EmployeeOfficeSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

management/base/views.py
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
import fiscalyear
import math
from io import BytesIO
from num2words import num2words
from xhtml2pdf import pisa


from management.models import Vendor, VendorAccount, VendorAddress, VendorContact

def vendor_home(request):
    template_path = "management/base/vendor/home.html"
    
    vendors = Vendor.objects.all().order_by('name')
    
    paginator = Paginator(vendors, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'xs': page_obj
    }

    return render(request, template_path, context)


def vendor_view(request, pk):
    template_path = "management/base/vendor/view.html"
    
    vendor = get_object_or_404(Vendor, pk=pk)
    
    vendor.address = VendorAddress.objects.filter(vendor = vendor)[0]
    vendor.accounts = VendorAccount.objects.filter(vendor = vendor)
    vendor.contacts = VendorContact.objects.filter(vendor = vendor)
    
    context = {
        'x': vendor
    }

    return render(request, template_path, context)

hr/templates/hr/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Summit Power Limited| ASPP</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">


  {% include 'hr/navbar.html' %}
  {% include 'hr/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block head %} Dashboard {% endblock %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        {% block content %}
        {% endblock %}
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2021-2022 <a href="http://www.deb-hub.com">www.deb-hub.com</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'admin-lte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'admin-lte/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'admin-lte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'admin-lte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'admin-lte/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'admin-lte/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin-lte/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'admin-lte/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>

{% block script %}
{% endblock %}
</body>
</html>

hr/templates/hr/navbar.html
{% load static %} 
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home:home' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'admin-lte/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

hr/templates/hr/sidebar.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-light-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{% static 'admin-lte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" class="brand-image img-circle elevation-3" style="opacity:.8">
    
      
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'admin-lte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">Alexander Pierce</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">

      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-header">Menus</li>
        
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link {% if menu == 'base' %} active {% endif %}">
            <i class="nav-icon fas fa-copy"></i>
            <p>
              Employee 
              <i class="fas fa-angle-left right"></i>
              <span class="badge badge-info right">6</span>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'employee:employee_home' %}" class="nav-link {% if submenu == 'vendor' %} active {% endif %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Employee</p>  
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'employee:office_home' %}" class="nav-link {% if submenu == 'vendor' %} active {% endif %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Office</p>  
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'employee:title_home' %}" class="nav-link {% if submenu == 'vendor' %} active {% endif %}">
                <i class="far fa-circle nav-icon"></i>
                <p>Title</p>  
              </a>
            </li>
           
          </ul>
        </li>
        
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>