home/urls.py
from django.urls import path
from home.views import home

app_name = "home"

urlpatterns = [
    path('', home, name='home'),
]

hr/urls.py
from django.urls import path
from hr import views

app_name = "hr"

urlpatterns = [
    
    
]

management/order/urls.py
from django.urls import path
from management.order import views

app_name = "order"

urlpatterns = [
    path('', views.order_home, name="order_home"),
    path('<int:pk>', views.order_view, name="order_view"),
    path('report/<int:pk>', views.order_report, name="order_report"),
]

management/urls.py
from django.urls import path
from management import views

app_name = "management"

urlpatterns = [
   



]

summit_office/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from management import views as mviews
from hr import views as hviews


router = routers.DefaultRouter()
router.register(r'approval', mviews.ApprovalViewSet)
router.register(r'quotation', mviews.QuotationViewSet)
router.register(r'quotation-item', mviews.QuotationItemViewSet)
router.register(r'titlequote', mviews.TitleQuoteViewSet)
router.register(r'titlequote-item', mviews.TitleQuoteItemViewSet)
router.register(r'purchaseorder', mviews.PurchaseOrderViewSet)
router.register(r'purchaseorder-term', mviews.PurchaseOrderTermViewSet)
router.register(r'paymentnote', mviews.PaymentNoteViewSet)
router.register(r'paymentnote-invoice', mviews.PaymentNoteInvoiceViewSet)
router.register(r'paymentnote-approval', mviews.PaymentNoteApprovalViewSet)
router.register(r'paymentothers', mviews.PaymentOthersViewSet)
router.register(r'paymentothers-item', mviews.PaymentOthersItemViewSet)

router.register(r'partitem', mviews.PartItemViewSet)
router.register(r'titleitem', mviews.TitleItemViewSet)
router.register(r'itemtype', mviews.ItemTypeViewSet)
router.register(r'measuringunit', mviews.MeasuringUnitViewSet)

router.register(r'vendor', mviews.VendorViewSet)
router.register(r'vendor-address', mviews.VendorAddressViewSet)
router.register(r'vendor-contact', mviews.VendorContactViewSet)
router.register(r'vendor-account', mviews.VendorAccountViewSet)


router.register(r'title', hviews.TitleViewSet)
router.register(r'office', hviews.OfficeViewSet)
router.register(r'employee', hviews.EmployeeViewSet)
router.register(r'employee-title', hviews.EmployeeTitleViewSet)
router.register(r'employee-office', hviews.EmployeeOfficeViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include("home.urls", namespace='home')),
    path('payment/', include("management.payment.urls", namespace="payment")),
    path('order/', include("management.order.urls", namespace="order")),
    path('approval/', include("management.approval.urls", namespace="approval")),
    path('base/', include("management.base.urls", namespace="management_base")),
    path('', include("hr.employee.urls", namespace="employee")),
    path('api/', include("management.urls", namespace="management")),
    path('api/', include("hr.urls", namespace="hr")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    template_path = "home/home.html"

    context = {

    }

    return render(request, template_path, context)

management/approval/views.py
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
import fiscalyear
import math
from io import BytesIO
from num2words import num2words
from xhtml2pdf import pisa
from hr.funs import EmpOffice, EmpTitle
from management.funs import FiscalYearNumber, FiscalYearText, link_callback

from management.models import *

def approval_home(request):
    template_path = "management/approval/home.html"

    approvals = Approval.objects.all().order_by('-id')

    paginator = Paginator(approvals, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'xs': page_obj
    }
    return render(request, template_path, context)

def approval_view(request, pk):
    template_path = "management/approval/view.html"
    
    approval = get_object_or_404(Approval, pk=pk)

    plant = EmpOffice(approval.raise_by.id, approval.date).stitle
    office = 'SPL'
        
    meta = {
        'ref': f"{office}/{plant}/Approval/{approval.ref()}",
        "title": EmpTitle(approval.raise_by.id, approval.date),
        "title2": EmpTitle(approval.submitted_to.id, approval.date)
    }


    context = {
       'x': approval, 
       'meta': meta
    }

    quotations = Quotation.objects.filter(approval=approval)
    titles = TitleQuote.objects.filter(approval=approval)
    sum_amount = 0
    
    if titles:
        title = titles[0]
        context['titles'] = title

        titleitems = TitleQuoteItem.objects.filter(title = title)
        
        context['titleItems'] = titleitems
        for item in titleitems:
            sum_amount = sum_amount + item.amount
        
        context['sum_amount'] = sum_amount
        context['txt_amount'] = num2words(math.floor(float(sum_amount) + 0.5), lang='en_IN').title()
   

    if quotations:
        count = quotations.count()
        context['xs']=quotations
        context['count']=count
        
        if count ==1:
            quotation = quotations[0]
            items = QuotationItem.objects.filter(quotation=quotation)
            total = vat = ait = vat_per = 0
            for x in items:
                total = total + x.price * x.quantity
                vat = vat + x.price * x.quantity * x.vat /100
                ait = ait + x.price * x.quantity * x.ait /100
                vat_per = vat_per + x.vat
            
            vat_per = vat_per / items.count()

            quotation.items = items
            quotation.total = total
            quotation.vat = vat
            quotation.ait = ait
            quotation.gross = total+vat
            quotation.vat_per = vat_per

            context['q1'] = quotation
            
        if count > 1:
            items = []
            y = []
            c = 0
            vats = []
            aits = []
            totals = []
            grosses = []
            vat_per = 0

            for i in range(count):
                itms = QuotationItem.objects.filter(quotation=quotations[i])
                total = vat = ait = 0
                for it in itms:
                    total = total + it.price * it.quantity
                    vat = vat + it.price * it.quantity * it.vat / 100
                    ait = ait + it.price * it.quantity * it.ait / 100
                    vat_per = it.vat
                
                totals.append(total)
                vats.append(vat)
                grosses.append(total+vat)
                aits.append(ait)
                items.append(itms)
                y.append(i)
                c = itms.count()
            text1 = f'VAT Amount({vat_per:.2f}%)'    
            text2 = "Total Amount including AIT"
            text3 = "Gross Amount"

            vats.insert(0, text1)
            totals.insert(0, text2)
            grosses.insert(0, text3)

            its = []
            prices = []
            vendors = []
            for i in range(c):
                its_dic = {}
                for j in y:
                    prices.append(items[j][i].price)
                    vendors.append(items[j][i].quotation.contact.vendor)
                its_dic["item"] = items[j][0].item
                its_dic["prices"] = prices
                its.append(its_dic)

            context["vendors"] = vendors
            context["vats"] = vats
            context["totals"] = totals
            context["grosses"] = grosses
            context["items"] = its
        
        for q in quotations:
            if q.selected:
                quotation_s = q
        
        adv_amount = quotation_s.advance_amount
        sec_amount = quotation_s.security_amount
        
        sitems = QuotationItem.objects.filter(quotation=quotation_s)
        
        sum_amount = 0
        for x in sitems:
            sum_amount = sum_amount + x.quantity * x.price * (1 + x.vat / 100)

        vendor = quotation_s.contact.vendor.name

        sl = 0
        p_advance = []
        if adv_amount > 0:
            sl = sl + 1
            p_advance.append(sl)
            p_advance.append(adv_amount)
            p_advance.append(vendor)
            p_advance.append("Pay In Advance with Purchase Order")

            context['p_advance'] = p_advance

        p_amount = []
        sl = sl + 1
        p_amount.append(sl)
        p_amount.append(math.floor(float(sum_amount - sec_amount - adv_amount) + 0.5))
        p_amount.append(vendor)
        p_amount.append("After submission of Original Bill")

        context['p_amount'] = p_amount

        p_security = []
        if sec_amount > 0:
            sl = sl + 1
            p_security.append(sl)
            p_security.append(sec_amount)
            p_security.append(vendor)

            context['p_security'] = p_security
        
    txt_amount = num2words(math.floor(float(sum_amount) + 0.5), lang='en_IN').title()
    txt_num = '{:,.2f}'.format(math.floor(float(sum_amount) + 0.5))
    salutation = f'Submitted for your kind approval for an amount of BDT ' + txt_num +'  (' + txt_amount + f') for above stated purpose'
    context['salutation'] = salutation
    
    return render(request, template_path, context)



def approval_report(request, pk):
    template_path = "management/approval/report.html"
    
    approval = get_object_or_404(Approval, pk=pk)
    
    
    plant = EmpOffice(approval.raise_by.id, approval.date)
    office = 'SPL'
        
    meta = {
        'ref': f"{office}/{plant.stitle}/Approval/{approval.ref()}",
        'office': plant.title,
        "title": EmpTitle(approval.raise_by.id, approval.date),
        "title2": EmpTitle(approval.submitted_to.id, approval.date)
    }


    context = {
       'x': approval, 
       'meta': meta
    }

    quotations = Quotation.objects.filter(approval=approval)
    titles = TitleQuote.objects.filter(approval=approval)
    sum_amount = 0

    if titles:
        title = titles[0]
        context['titles'] = title
        
        titleitems = TitleQuoteItem.objects.filter(title = title)
        context['titleItems'] = titleitems
        for item in titleitems:
            sum_amount = sum_amount + item.amount
        context['sum_amount'] = sum_amount
        context['txt_amount'] = num2words(math.floor(float(sum_amount) + 0.5), lang='en_IN').title()

    if quotations:
        count = quotations.count()
        context['xs']=quotations
        context['count']=count
        
        
        if count ==1:
            quotation = quotations[0]
            items = QuotationItem.objects.filter(quotation=quotation)
            total = vat = ait = vat_per = 0
            for x in items:
                total = total + x.price * x.quantity
                vat = vat + x.price * x.quantity * x.vat /100
                ait = ait + x.price * x.quantity * x.ait /100
                vat_per = vat_per + x.vat
            
            vat_per = vat_per / items.count()

            quotation.items = items
            quotation.total = total
            quotation.vat = vat
            quotation.ait = ait
            quotation.gross = total+vat
            quotation.vat_per = vat_per

            context['q1'] = quotation
            print(total, vat, ait, vat_per)
        if count > 1:
            items = []
            y = []
            c = 0
            vats = []
            aits = []
            totals = []
            grosses = []
            vat_per = 0

            for i in range(count):
                itms = QuotationItem.objects.filter(quotation=quotations[i])
                total = vat = ait = 0
                for it in itms:
                    total = total + it.price * it.quantity
                    vat = vat + it.price * it.quantity * it.vat / 100
                    ait = ait + it.price * it.quantity * it.ait / 100
                    vat_per = it.vat
                
                totals.append(total)
                vats.append(vat)
                grosses.append(total+vat)
                aits.append(ait)
                items.append(itms)
                y.append(i)
                c = itms.count()
            text1 = f'VAT Amount({vat_per:.2f}%)'    
            text2 = "Total Amount including AIT"
            text3 = "Gross Amount"

            vats.insert(0, text1)
            totals.insert(0, text2)
            grosses.insert(0, text3)

            its = []
            prices = []
            vendors = []
            for i in range(c):
                its_dic = {}
                for j in y:
                    prices.append(items[j][i].price)
                    vendors.append(items[j][i].quotation.contact.vendor)
                its_dic["item"] = items[j][0].item
                its_dic["prices"] = prices
                its.append(its_dic)

            context["vendors"] = vendors
            context["vats"] = vats
            context["totals"] = totals
            context["grosses"] = grosses
            context["items"] = its
        

management/base/views.py
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
import fiscalyear
import math
from io import BytesIO
from num2words import num2words
from xhtml2pdf import pisa


from management.models import Vendor, VendorAccount, VendorAddress, VendorContact

def vendor_home(request):
    template_path = "management/base/vendor/home.html"
    
    vendors = Vendor.objects.all().order_by('name')
    
    paginator = Paginator(vendors, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'xs': page_obj
    }

    return render(request, template_path, context)


def vendor_view(request, pk):
    template_path = "management/base/vendor/view.html"
    
    vendor = get_object_or_404(Vendor, pk=pk)
    
    vendor.address = VendorAddress.objects.filter(vendor = vendor)[0]
    vendor.accounts = VendorAccount.objects.filter(vendor = vendor)
    vendor.contacts = VendorContact.objects.filter(vendor = vendor)
    
    context = {
        'x': vendor
    }

    return render(request, template_path, context)

management/templates/management/order/home.html
{% extends 'management/base.html'%}

{% block head %} {{title}} {% endblock %}

{% block content %}
<div class="d-grid gap-2 ">
    <div class="card ">
        <div class="card-body">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th width="5%">#</th>
                        <th width="12%">Ref no</th>
                        <th width="12%">Date</th>
                        <th> Contact</th>
                        <th>Vendor </th>
                        <th width="12%">Amount </th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for x in xs %}
                    <tr>
                        <td>{{ x.id }}</td>
                        <td><a href="{% url 'order:order_view' x.id %}">{{ x.ref}}</a> </td>
                        <td>{{ x.date|date:"d/m/Y"}}</td>
                        <td>{{ x.quotation.contact.name }}, {{ x.quotation.contact.title }}</td>
                        <td>{{ x.quotation.contact.vendor.name }}</td>
                        <td style="text-align: end;">{{ x.amount |floatformat:"2g" }}</td>
                        
                    </tr>
                    <tr>
                        
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            <hr>
            <div class="pagination justify-content-md-center">
                <span class="step-links">
                    {% if xs.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ xs.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ xs.number }} of {{ xs.paginator.num_pages }}.
                    </span>

                    {% if xs.has_next %}
                    <a href="?page={{ xs.next_page_number }}">next</a>
                    <a href="?page={{ xs.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block script %}
{% endblock %}

management/templates/management/order/view.html
{% extends 'management/base.html'%}

{% block head %} {{title}} {% endblock %}

{% block content %}
<div class="d-grid gap-2 d-md-flex justify-content-md-end">

    <a href="{% url 'order:order_report' x.id %}" target="_blank" style="min-width:100px;" class="btn btn-info m-1">Report</a>
    <a href="{% url 'order:order_home' %}" style="min-width:100px;" class="btn btn-dark m-1">Back</a>
    
</div>
<div class="d-grid gap-2 ">
    <div class="card ">
        <div class="card-body">
            <table class="table table-borderless table-sm">
                <tr>
                    <tr>
                        <td rowspan="4" style="width:35%">
                            Order To: <br/>
                            {{x.quotation.contact.vendor.name}} <br/>
                            {{x.address.address}}<br/>
                            {{x.address.district}}, {{x.address.country}}
                        </td>
                        <td></td>
                        <td style="width:12%">Reference</td>
                        <td style="width:25%">{{x.ref}}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Date</td>
                        <td>{{x.date|date:"d/m/Y"}}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Your Ref</td>
                        <td>{{x.quotation.reference}}</td>
                    </tr>
                    <tr>
                        
                        <td></td>
                        <td>Your Ref Date</td>
                        <td>{{x.quotation.date|date:"d/m/Y"}}</td>
                    </tr>
                    <tr>
                        <td>
                            <u> Shipping/Work Address: </u> <br/>
                            {{x.office.title}} <br/>
                            {{x.office.address}} <br/>
                            {{x.office.contact}} <br/>
                            {{x.office.email}}
                        </td>
                        <td></td>
                        <td>Contact</td>
                        <td>{{x.quotation.contact.name}}, {{x.quotation.contact.title}} <br/>
                            {{x.quotation.contact.mobile}}  <br/>
                            {{x.quotation.contact.email}}
                        </td>
                        
                    </tr>
                    

                </tr>
            </table>
            
            				
            <br>
            {% if  x.service %}
            <table class="table table-sm ">
                <tr>
                    <td style="width: 5%;">#</td>
                    
                    <td>
                        Item Description <br/>
                        Work Description
                    </td>
                    

                    
                    <td>
                        Quantity
                    </td>
                    <td>
                        Unit
                    </td>
                    <td>
                        Unit Price
                    </td>
                    <td>
                        Line Amount
                    </td>
                </tr>
                {% for x1 in xs %}
                <tr>
                    <td>{{forloop.counter}}</td>
  

                    
                    <td>{{x1.item.description|safe}} </td>
                    
                    
                    <td>{{x1.quantity}}</td>
                    <td>{{x1.item.unit}}</td>
                    <td>{{x1.price}}</td>
                    <td>{{x1.line_amount}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="5">Total Amount including AIT</td>
                    <td>{{x.total}}</td>
                </tr>
                <tr>
                    <td colspan="5">VAT({{x.vat_per}} %) Amount</td>
                    <td>{{x.vat}}</td>
                </tr>
                <tr>
                    <td colspan="5">Gross Amount</td>
                    <td>{{x.gross}}</td>
                </tr>
                <tr>
                    <td colspan="6">In word: {{x.txt_amount}}</td>
                </tr>
            </table>
            {% else %}
            <table class="table table-sm ">
                <tr>
                    <td style="width: 5%;">#</td>
                    
                   
                    
                    <td>	
                        Part No <br/>
                        Item Code
                    </td>
                    <td>
                        Item Description <br/>
                        Work Description
                    </td>
                    
                    <td>
                        Quantity
                    </td>
                    <td>
                        Unit
                    </td>
                    <td>
                        Unit Price
                    </td>
                    <td>
                        Line Amount
                    </td>
                </tr>
                {% for x1 in xs %}
                <tr>
                    <td>{{forloop.counter}}</td>
  
                    <td>{{x1.item.part_no}} <br/> {{x1.item.rev_part}}</td>
                    <td>{{x1.item.part_name|safe}} <br/> {{x1.item.description|safe}} </td>
                    
                    <td>{{x1.quantity}}</td>
                    <td>{{x1.item.unit}}</td>
                    <td>{{x1.price}}</td>
                    <td>{{x1.line_amount}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="6">Total Amount including AIT</td>
                    <td>{{x.total}}</td>
                </tr>
                <tr>
                    <td colspan="6">VAT({{x.vat_per}} %) Amount</td>
                    <td>{{x.vat}}</td>
                </tr>
                <tr>
                    <td colspan="6">Gross Amount</td>
                    <td>{{x.gross}}</td>
                </tr>
                <tr>
                    <td colspan="7">In word: {{x.txt_amount}}</td>
                </tr>
            </table>
            {% endif %}
           <br/>
            <table class="table table-sm table-borderless">
                <p>Terms & Conditions:</p>
                {% for y in x.terms %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{y.legend}}</td>
                    <td>  {% if y.newtext  %}
                     {{y.newtext|safe}}
                    {% endif  %}
                    {% if y.text  %}
                    {{y.text|safe }}
                    {% endif  %}
                    </td>
                </tr>
                {% endfor %}
            </table>


            <p> ______________________ <br/>
                {{x.order_by.name}}  <br/>
                {{x.order_by_title.title}}  <br/>
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}